/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.supp.UI;

import DAO.nhanVienDao;
import DAO.sanPhamDAO;
import com.supp.Entity.NhanVien;
import com.supp.Util.Auth;
import com.supp.Util.MsgBox;
import com.supp.Util.XImage;
import java.awt.Color;
import java.io.File;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initComponents();
        init();
        setBackground(new Color(0, 0, 0, 0));
        menu1.initMoving(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelBorder1 = new com.supp.Swing.PanelBorder();
        lblHome = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblKhachHang = new javax.swing.JLabel();
        lblThongKe = new javax.swing.JLabel();
        lblHoaDon = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        menu1 = new com.supp.Component.Menu();
        pnlHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAnhnen = new javax.swing.JLabel();
        pnlNhanVien = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblAnhNV = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblTenNV = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        lblSDTNV = new javax.swing.JLabel();
        txtSDTNV = new javax.swing.JTextField();
        lblEmailNV = new javax.swing.JLabel();
        txtEmailNV = new javax.swing.JTextField();
        rdoNhanVien = new javax.swing.JRadioButton();
        lblVaiTroNV = new javax.swing.JLabel();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoAdmin = new javax.swing.JRadioButton();
        btnChonAnhNV = new javax.swing.JButton();
        btnThemNV = new javax.swing.JButton();
        btnUpdateNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        lvlMatKhauNV = new javax.swing.JLabel();
        txtPassNV = new javax.swing.JPasswordField();
        btnFirstNV = new javax.swing.JButton();
        btnPrevNV = new javax.swing.JButton();
        btnNextNV = new javax.swing.JButton();
        btnLastNV = new javax.swing.JButton();
        btnMoiNV = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemNV = new javax.swing.JTextField();
        pnlProduct = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblAnhSP = new javax.swing.JLabel();
        lblMaNV1 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        lblTenNV1 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        lblSDTNV1 = new javax.swing.JLabel();
        txtTonKho = new javax.swing.JTextField();
        lblEmailNV1 = new javax.swing.JLabel();
        txtNhaSX = new javax.swing.JTextField();
        lblVaiTroNV1 = new javax.swing.JLabel();
        btnChonAnhSP = new javax.swing.JButton();
        btnThemNV1 = new javax.swing.JButton();
        btnUpdateNV1 = new javax.swing.JButton();
        btnXoaNV1 = new javax.swing.JButton();
        lvlMatKhauNV1 = new javax.swing.JLabel();
        txtMaNV_SP = new javax.swing.JPasswordField();
        btnFirstSP = new javax.swing.JButton();
        btnPrevSP = new javax.swing.JButton();
        btnNextSP = new javax.swing.JButton();
        btnLastSP = new javax.swing.JButton();
        btnMoiNV1 = new javax.swing.JButton();
        txtNgaySX = new javax.swing.JTextField();
        lblVaiTroNV2 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtTimKiemSP = new javax.swing.JTextField();
        pnlKhachHang = new javax.swing.JPanel();
        pnlThongKe = new javax.swing.JPanel();
        pnlHoaDon = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home64.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        panelBorder1.add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 80));

        lblNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee64.png"))); // NOI18N
        lblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienMouseClicked(evt);
            }
        });
        panelBorder1.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 190, 60));

        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product64.png"))); // NOI18N
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
        });
        panelBorder1.add(lblProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 70));

        lblKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customer64.png"))); // NOI18N
        lblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangMouseClicked(evt);
            }
        });
        panelBorder1.add(lblKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 60));

        lblThongKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thongke64.png"))); // NOI18N
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });
        panelBorder1.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 190, 70));

        lblHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoadon64.png"))); // NOI18N
        lblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoaDonMouseClicked(evt);
            }
        });
        panelBorder1.add(lblHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 190, 60));

        lblSignOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout32.png"))); // NOI18N
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignOutMouseClicked(evt);
            }
        });
        panelBorder1.add(lblSignOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 600, 60, 60));

        jButton1.setText("Đổi MK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBorder1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, -1));
        panelBorder1.add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 663));

        getContentPane().add(panelBorder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlHome.setBackground(new java.awt.Color(204, 204, 255));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome, Admin");
        pnlHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        lblAnhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home1000x664.png"))); // NOI18N
        pnlHome.add(lblAnhnen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 1000, -1));

        getContentPane().add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pnlNhanVien.setBackground(new java.awt.Color(204, 204, 0));

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 664));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAnhNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhNVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnhNV, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnhNV, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNV.setText("Mã nhân viên:");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("Tên nhân viên:");

        lblSDTNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDTNV.setText("Số điện thoại:");

        lblEmailNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailNV.setText("Email:");

        buttonGroup1.add(rdoNhanVien);
        rdoNhanVien.setText("Nhân viên");
        rdoNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNhanVienActionPerformed(evt);
            }
        });

        lblVaiTroNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVaiTroNV.setText("Vai trò:");

        buttonGroup1.add(rdoQuanLy);
        rdoQuanLy.setText("Quản lý");

        buttonGroup1.add(rdoAdmin);
        rdoAdmin.setText("Admin");

        btnChonAnhNV.setText("Chọn ảnh");
        btnChonAnhNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhNVActionPerformed(evt);
            }
        });

        btnThemNV.setText("Thêm nhân viên");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        btnUpdateNV.setText("Cập nhật nhân viên");
        btnUpdateNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNVActionPerformed(evt);
            }
        });

        btnXoaNV.setText("Xóa nhân viên");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });

        lvlMatKhauNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlMatKhauNV.setText("Mật khẩu:");

        btnFirstNV.setText("|<");
        btnFirstNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstNVActionPerformed(evt);
            }
        });

        btnPrevNV.setText("<<");
        btnPrevNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevNVActionPerformed(evt);
            }
        });

        btnNextNV.setText(">>");
        btnNextNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextNVActionPerformed(evt);
            }
        });

        btnLastNV.setText(">|");
        btnLastNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastNVActionPerformed(evt);
            }
        });

        btnMoiNV.setText("Mới");
        btnMoiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnChonAnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnFirstNV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevNV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextNV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLastNV, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVaiTroNV)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdoNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lblSDTNV)
                    .addComponent(txtSDTNV, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lblEmailNV)
                    .addComponent(txtEmailNV, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoiNV))
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lvlMatKhauNV)
                    .addComponent(txtPassNV))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblMaNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(lvlMatKhauNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTenNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSDTNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDTNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnChonAnhNV)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEmailNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaiTroNV)
                    .addComponent(btnFirstNV)
                    .addComponent(btnPrevNV)
                    .addComponent(btnNextNV)
                    .addComponent(btnLastNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNhanVien)
                    .addComponent(rdoQuanLy)
                    .addComponent(rdoAdmin))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV)
                    .addComponent(btnUpdateNV)
                    .addComponent(btnXoaNV)
                    .addComponent(btnMoiNV))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        tabs.addTab("Thông tin chi tiết", jPanel2);

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NV", "MẬT KHẨU", "TÊN NV", "SDT", "EMAIL", "VAI TRÒ", "Hinh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search.png"))); // NOI18N

        txtTimKiemNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemNVKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiemNV))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        tabs.addTab("Danh sách nhân viên", jPanel3);

        javax.swing.GroupLayout pnlNhanVienLayout = new javax.swing.GroupLayout(pnlNhanVien);
        pnlNhanVien.setLayout(pnlNhanVienLayout);
        pnlNhanVienLayout.setHorizontalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        pnlNhanVienLayout.setVerticalGroup(
            pnlNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        getContentPane().add(pnlNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pnlProduct.setBackground(new java.awt.Color(51, 204, 255));

        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 664));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblAnhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnhSP, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
        );

        lblMaNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMaNV1.setText("Mã sản phẩm:");

        lblTenNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV1.setText("Tên sản phẩm:");

        lblSDTNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSDTNV1.setText("Tồn kho:");

        lblEmailNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmailNV1.setText("Nhà sản xuất:");

        lblVaiTroNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVaiTroNV1.setText("Ngày sản xuất:");

        btnChonAnhSP.setText("Chọn ảnh");
        btnChonAnhSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonAnhSPActionPerformed(evt);
            }
        });

        btnThemNV1.setText("Thêm sản phẩm");
        btnThemNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNV1ActionPerformed(evt);
            }
        });

        btnUpdateNV1.setText("Cập nhật sản phẩm");
        btnUpdateNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNV1ActionPerformed(evt);
            }
        });

        btnXoaNV1.setText("Xóa sản phẩm");
        btnXoaNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNV1ActionPerformed(evt);
            }
        });

        lvlMatKhauNV1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lvlMatKhauNV1.setText("Mã nhân viên:");

        btnFirstSP.setText("|<");
        btnFirstSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstSPActionPerformed(evt);
            }
        });

        btnPrevSP.setText("<<");
        btnPrevSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevSPActionPerformed(evt);
            }
        });

        btnNextSP.setText(">>");
        btnNextSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextSPActionPerformed(evt);
            }
        });

        btnLastSP.setText(">|");
        btnLastSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastSPActionPerformed(evt);
            }
        });

        btnMoiNV1.setText("Mới");
        btnMoiNV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiNV1ActionPerformed(evt);
            }
        });

        lblVaiTroNV2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVaiTroNV2.setText("Giá:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnChonAnhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnFirstSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLastSP, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblVaiTroNV2)
                    .addComponent(txtNgaySX)
                    .addComponent(lblVaiTroNV1)
                    .addComponent(lblMaNV1)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lblSDTNV1)
                    .addComponent(txtTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lblEmailNV1)
                    .addComponent(txtNhaSX, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnThemNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMoiNV1))
                    .addComponent(lblTenNV1)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(lvlMatKhauNV1)
                    .addComponent(txtMaNV_SP)
                    .addComponent(txtGia))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnChonAnhSP))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMaNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lvlMatKhauNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaNV_SP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTenNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSDTNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmailNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhaSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVaiTroNV1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgaySX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblVaiTroNV2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFirstSP)
                            .addComponent(btnPrevSP)
                            .addComponent(btnNextSP)
                            .addComponent(btnLastSP)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemNV1)
                    .addComponent(btnUpdateNV1)
                    .addComponent(btnXoaNV1)
                    .addComponent(btnMoiNV1))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thông tin chi tiết", jPanel5);

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SP", "MÃ NV", "TÊN SP", "TỒN KHO", "NHÀ SX", "NGÀY SX", "GIÁ", "HÌNH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSanPham);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search.png"))); // NOI18N

        txtTimKiemSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemSPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiemSP))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("Danh sách nhân viên", jPanel7);

        javax.swing.GroupLayout pnlProductLayout = new javax.swing.GroupLayout(pnlProduct);
        pnlProduct.setLayout(pnlProductLayout);
        pnlProductLayout.setHorizontalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        pnlProductLayout.setVerticalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );

        getContentPane().add(pnlProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pnlKhachHang.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout pnlKhachHangLayout = new javax.swing.GroupLayout(pnlKhachHang);
        pnlKhachHang.setLayout(pnlKhachHangLayout);
        pnlKhachHangLayout.setHorizontalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlKhachHangLayout.setVerticalGroup(
            pnlKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        getContentPane().add(pnlKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pnlThongKe.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout pnlThongKeLayout = new javax.swing.GroupLayout(pnlThongKe);
        pnlThongKe.setLayout(pnlThongKeLayout);
        pnlThongKeLayout.setHorizontalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlThongKeLayout.setVerticalGroup(
            pnlThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        getContentPane().add(pnlThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pnlHoaDon.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 664, Short.MAX_VALUE)
        );

        getContentPane().add(pnlHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1000, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        pnlNhanVien.setVisible(false);
        pnlHome.setVisible(true);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(false);
        pnlHoaDon.setVisible(false);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pnlNhanVien.setVisible(false);
        pnlHome.setVisible(true);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(false);
        pnlHoaDon.setVisible(false);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked
        pnlNhanVien.setVisible(false);
        pnlHome.setVisible(false);
        pnlProduct.setVisible(true);
        pnlKhachHang.setVisible(false);
        pnlHoaDon.setVisible(false);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_lblProductMouseClicked

    private void lblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangMouseClicked
        pnlNhanVien.setVisible(false);
        pnlHome.setVisible(false);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(true);
        pnlHoaDon.setVisible(false);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_lblKhachHangMouseClicked

    private void lblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoaDonMouseClicked
        pnlNhanVien.setVisible(false);
        pnlHome.setVisible(false);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(false);
        pnlHoaDon.setVisible(true);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_lblHoaDonMouseClicked

    private void lblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienMouseClicked
        pnlHoaDon.setVisible(false);
        pnlHome.setVisible(false);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(false);
        pnlNhanVien.setVisible(true);
        pnlThongKe.setVisible(false);
    }//GEN-LAST:event_lblNhanVienMouseClicked

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        pnlHoaDon.setVisible(false);
        pnlHome.setVisible(false);
        pnlProduct.setVisible(false);
        pnlKhachHang.setVisible(false);
        pnlHoaDon.setVisible(false);
        pnlThongKe.setVisible(true);
    }//GEN-LAST:event_lblThongKeMouseClicked

    private void lblSignOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseClicked
        this.dispose();
        new LoginJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblSignOutMouseClicked

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        if (evt.getClickCount() == 2) {
            this.rowNV = tblNhanVien.getSelectedRow();
            this.editNhanVien();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        if(validateFormNV()){
            insertNV();
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnUpdateNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNVActionPerformed
        if(validateFormNV()){
            updateNV();
        }
    }//GEN-LAST:event_btnUpdateNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        deleteNV();
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnFirstNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstNVActionPerformed
        firstNV();
    }//GEN-LAST:event_btnFirstNVActionPerformed

    private void btnPrevNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevNVActionPerformed
        prevNV();
    }//GEN-LAST:event_btnPrevNVActionPerformed

    private void btnNextNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextNVActionPerformed
        nextNV();
    }//GEN-LAST:event_btnNextNVActionPerformed

    private void btnLastNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastNVActionPerformed
        lastNV();
    }//GEN-LAST:event_btnLastNVActionPerformed

    private void lblAnhNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhNVMouseClicked
    
    }//GEN-LAST:event_lblAnhNVMouseClicked

    private void rdoNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNhanVienActionPerformed
        
    }//GEN-LAST:event_rdoNhanVienActionPerformed

    private void btnMoiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiNVActionPerformed
        clearFormNV();
    }//GEN-LAST:event_btnMoiNVActionPerformed

    private void txtTimKiemNVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemNVKeyReleased
        timKiemNV();
    }//GEN-LAST:event_txtTimKiemNVKeyReleased

    private void btnChonAnhNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhNVActionPerformed
        chonAnhNV();
    }//GEN-LAST:event_btnChonAnhNVActionPerformed

    private void lblAnhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAnhSPMouseClicked

    private void btnChonAnhSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonAnhSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonAnhSPActionPerformed

    private void btnThemNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNV1ActionPerformed

    private void btnUpdateNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateNV1ActionPerformed

    private void btnXoaNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaNV1ActionPerformed

    private void btnFirstSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirstSPActionPerformed

    private void btnPrevSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevSPActionPerformed

    private void btnNextSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextSPActionPerformed

    private void btnLastSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLastSPActionPerformed

    private void btnMoiNV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiNV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoiNV1ActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void txtTimKiemSPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemSPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSPKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnhNV;
    private javax.swing.JButton btnChonAnhSP;
    private javax.swing.JButton btnFirstNV;
    private javax.swing.JButton btnFirstSP;
    private javax.swing.JButton btnLastNV;
    private javax.swing.JButton btnLastSP;
    private javax.swing.JButton btnMoiNV;
    private javax.swing.JButton btnMoiNV1;
    private javax.swing.JButton btnNextNV;
    private javax.swing.JButton btnNextSP;
    private javax.swing.JButton btnPrevNV;
    private javax.swing.JButton btnPrevSP;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThemNV1;
    private javax.swing.JButton btnUpdateNV;
    private javax.swing.JButton btnUpdateNV1;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JButton btnXoaNV1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAnhNV;
    private javax.swing.JLabel lblAnhSP;
    private javax.swing.JLabel lblAnhnen;
    private javax.swing.JLabel lblEmailNV;
    private javax.swing.JLabel lblEmailNV1;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblKhachHang;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaNV1;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblSDTNV;
    private javax.swing.JLabel lblSDTNV1;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTenNV1;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblVaiTroNV;
    private javax.swing.JLabel lblVaiTroNV1;
    private javax.swing.JLabel lblVaiTroNV2;
    private javax.swing.JLabel lvlMatKhauNV;
    private javax.swing.JLabel lvlMatKhauNV1;
    private com.supp.Component.Menu menu1;
    private com.supp.Swing.PanelBorder panelBorder1;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlKhachHang;
    private javax.swing.JPanel pnlNhanVien;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JRadioButton rdoAdmin;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtEmailNV;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JPasswordField txtMaNV_SP;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNgaySX;
    private javax.swing.JTextField txtNhaSX;
    private javax.swing.JPasswordField txtPassNV;
    private javax.swing.JTextField txtSDTNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiemNV;
    private javax.swing.JTextField txtTimKiemSP;
    private javax.swing.JTextField txtTonKho;
    // End of variables declaration//GEN-END:variables
    nhanVienDao nvdao = new nhanVienDao();
    sanPhamDAO spdao = new sanPhamDAO();
    
    int rowNV = -1;
    int rowSP = -1;
    //                                    NHÂN VIÊN

    void init() {
        fillTableNV();
        updateStatusNV();
    }

    void timKiemNV(){
        this.fillTableNV();
        this.clearFormNV();
        this.rowNV = -1;
        updateStatusNV();
    }
    
    void fillTableNV() {
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiemNV.getText();
            List<NhanVien> list = nvdao.selectByKeyword(keyword); //đọc dữ liệu từ CSDL
            for (NhanVien nv : list) {
                Object[] row = {nv.getMaNV(), nv.getMatKhau(), nv.getTenNV(),
                    nv.getDienThoai(), nv.getEmail(), nv.getVaiTro(), nv.getHinhAnh()};
                model.addRow(row); //thêm từng hàng vào JTable
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
            System.out.println(e);
        }
    }

    void editNhanVien() {
        String manv = (String) tblNhanVien.getValueAt(this.rowNV, 0);
        NhanVien nv = nvdao.selectById(manv);
        this.setFormNV(nv);
        tabs.setSelectedIndex(0);
        this.updateStatusNV();
    }

    void setFormNV(NhanVien nv) {
        txtMaNV.setText(nv.getMaNV());
        txtPassNV.setText(nv.getMatKhau());
        txtTenNV.setText(nv.getTenNV());
        txtSDTNV.setText(nv.getDienThoai());
        txtEmailNV.setText(nv.getEmail());


        if (nv.getVaiTro().equals("Admin")) {
            rdoAdmin.setSelected(true);
        } else if (nv.getVaiTro().equals("Quản lý")) {
            rdoQuanLy.setSelected(true);
        } else {
            rdoNhanVien.setSelected(true);
        }
        if (nv.getHinhAnh() != null) {
            lblAnhNV.setToolTipText(nv.getHinhAnh());
            lblAnhNV.setIcon(XImage.read(nv.getHinhAnh()));
        }

    }

    NhanVien getFormNV() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setMatKhau(new String(txtPassNV.getPassword()));
        nv.setTenNV(txtTenNV.getText());
        nv.setDienThoai(txtSDTNV.getText());
        nv.setEmail(txtEmailNV.getText());
        if (rdoAdmin.isSelected()) {
            nv.setVaiTro("Admin");
        } else if (rdoQuanLy.isSelected()) {
            nv.setVaiTro("Quản lý");
        } else if (rdoNhanVien.isSelected()) {
            nv.setVaiTro("Nhân viên");
        }
        nv.setHinhAnh(lblAnhNV.getToolTipText());
        System.out.println(lblAnhNV.getToolTipText());
        return nv;
    }

    void updateStatusNV() {
        boolean edit = (this.rowNV >= 0);
        boolean first = (this.rowNV == 0);
        boolean last = (this.rowNV == tblNhanVien.getRowCount() - 1);

        //Trạng thái form
        txtMaNV.setEditable(!edit);
        btnThemNV.setEnabled(!edit);
        btnUpdateNV.setEnabled(edit);
        btnUpdateNV.setEnabled(edit);
        //Trạng thái điều hướng
        btnFirstNV.setEnabled(edit && !first);
        btnPrevNV.setEnabled(edit);
        btnNextNV.setEnabled(edit);
        btnLastNV.setEnabled(edit && !last);
    }

    void clearFormNV() {
        NhanVien nv = new NhanVien();
        this.setFormNV(nv);
        rdoNhanVien.setSelected(true);
        lblAnhNV.setIcon(null);
        this.rowNV = -1;
        updateStatusNV();
    }

    void insertNV() {
        NhanVien nv = getFormNV();
        try {
            nvdao.insert(nv);
            this.fillTableNV();
            this.clearFormNV();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
            System.out.println(e);
        }
    }

    void updateNV() {
        NhanVien nv = getFormNV();
        try {
            nvdao.update(nv);
            this.fillTableNV();
            this.clearFormNV();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
            System.out.println(e);
        }
    }

    void deleteNV() {
        String manv = txtMaNV.getText();
        if (!Auth.isAdmin() && !Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền được xóa!");
            System.out.println(Auth.isAdmin()+"\n"+Auth.isManager());
        } else {
            if (manv.equals(Auth.user.getMaNV())) {
                MsgBox.alert(this, "Bạn không được xóa chính mình!");
            } else if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa nhân viên này ?")) {
                try {
                    nvdao.delete(manv);
                    this.fillTableNV();
                    this.clearFormNV();
                    MsgBox.alert(this, "Xóa nhân viên thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa nhân viên thất bại");
                    System.out.println(e);
                }
            }
        }
    }

    void firstNV() {
        this.rowNV = 0;
        tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        this.editNhanVien();
        System.out.println(rowNV);
    }

    void nextNV() {
        if (this.rowNV < tblNhanVien.getRowCount() - 1) {
            this.rowNV++;
            this.editNhanVien();
            tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        } else {
            this.rowNV = 0;
            this.editNhanVien();
            tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        }
    }

    void prevNV() {
        if (this.rowNV > 0) {
            this.rowNV--;
            this.editNhanVien();
            tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        } else {
            this.rowNV = tblNhanVien.getRowCount() - 1;
            this.editNhanVien();
            tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        }
        System.out.println(rowNV);
    }

    void lastNV() {
        this.rowNV = tblNhanVien.getRowCount() - 1;
        this.editNhanVien();
        tblNhanVien.setRowSelectionInterval(rowNV, rowNV);
        System.out.println(rowNV);
    }

    void chonAnhNV() {
        String path = "C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\ProjectNMKTPM\\src\\images";
        JFileChooser fileChooser = new JFileChooser(path);
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {  
            fileChooser.setCurrentDirectory(new java.io.File(path));
            File file = fileChooser.getSelectedFile();
            XImage.save(file); //lưu hình vào thư mục logos
            ImageIcon icon = XImage.read(file.getName()); //đọc hình từ logo
            lblAnhNV.setIcon(icon);
            lblAnhNV.setToolTipText(file.getName()); //giữ tên hình trong tooltip
        }
    }
    
    boolean validateFormNV(){
        if(txtMaNV.getText().isEmpty()){
            MsgBox.alert(this, "Mã nhân viên không được trống!");
            return false;
        }
        if(new String(txtPassNV.getPassword()).isEmpty()){
            MsgBox.alert(this, "Mật khẩu không được trống!");
            return false;
        }
        if(txtTenNV.getText().isEmpty()){
            MsgBox.alert(this, "Tên nhân viên không được trống!");
            return false;
        }
        if(txtSDTNV.getText().isEmpty()){
            MsgBox.alert(this, "Số điện thoại nhân viên không được trống!");
            return false;
        }
        if(txtEmailNV.getText().isEmpty()){
            MsgBox.alert(this, "Email nhân viên không được trống!");
            return false;
        }
        if(!rdoAdmin.isSelected() && !rdoQuanLy.isSelected() && !rdoNhanVien.isSelected()){
            MsgBox.alert(this, "Vai trò nhân viên không được trống!");
            return false;
        }
        return true;
    }
    
    
    
    //                                  SẢN PHẨM

}
